// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Attendance   string
	Blobs        string
	Friends      string
	Integrations string
	Users        string
}{
	Attendance:   "attendance",
	Blobs:        "blobs",
	Friends:      "friends",
	Integrations: "integrations",
	Users:        "users",
}
